# Generated by Django 2.1.1 on 2018-09-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.BigIntegerField(verbose_name='identifiant strava')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('distance', models.FloatField(verbose_name='distance')),
                ('moving_time', models.IntegerField(verbose_name='durée de déplacement')),
                ('elapsed_time', models.IntegerField(verbose_name="durée de l'activité")),
                ('total_elevation_gain', models.FloatField(blank=True, null=True, verbose_name='dénivelé')),
                ('elev_high', models.FloatField(blank=True, null=True, verbose_name='altitude maximale')),
                ('elev_low', models.FloatField(blank=True, null=True, verbose_name='altitude minimale')),
                ('type', models.IntegerField(choices=[(1, 'Natation'), (2, 'Vélo'), (3, 'Course à pied'), (4, 'Football'), (5, 'Autre')], verbose_name='sport')),
                ('date', models.DateTimeField(verbose_name="date de l'activité")),
                ('average_speed', models.FloatField(verbose_name='vitesse moyenne')),
                ('max_speed', models.FloatField(verbose_name='vitesse maximale')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('average_heartrate', models.IntegerField(blank=True, null=True, verbose_name='fréquence cardiaque moyenne')),
                ('max_heartrate', models.IntegerField(blank=True, null=True, verbose_name='fréquence cardiaque maximum')),
            ],
        ),
        migrations.CreateModel(
            name='Synchronization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date de la synchronisation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('strava_id',)},
        ),
    ]
